spring:
  profiles:
    active: local
  application:
    name: transactions-service
  kafka:
    bootstrap-servers: localhost:9092   # adjust for your environment
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    streams:
      application-id: transactions-service
      replication-factor: 1               # use 3 in production
      properties:
        commit.interval.ms: 5000          # frequency of flushing state store
        cache.max.bytes.buffering: 10485760 # 10 MB cache
        num.stream.threads: 3             # parallelism
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$ByteArraySerde
        processing.guarantee: exactly_once_v2  # exactly-once semantics
      state-dir: ./tmp/kafka-streams/state
  output:
    ansi:
      enabled: always


otel:
  traces:
    exporter: none
  metrics:
    exporter: none
  logs:
    exporter: console
  instrumentation:
    micrometer:
      enabled: true
    http:
      client:
        emit-experimental-telemetry: true
  sdk:
    disabled: false
  propagators: tracecontext,baggage,b3

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
      remote-fields:
        - correlation-id
        - request-id
    propagation:
      consume: w3c,b3,b3_multi
      produce: w3c,b3,b3_multi