version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      - run:
          name: Run Tests with Maven
          command: mvn verify -Dspring.profiles.active=test

      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

workflows:
  build-workflow:
    jobs:
      - build-and-test
