apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-storage-pvc
  labels:
    app: kafka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi