services:
    dbmicro:
        image: postgres:16
        container_name: dbmicro
        restart: on-failure
        ports:
            - "5440:5432"
        networks:
            - api-micro
        environment:
            - POSTGRES_USER=micro
            - POSTGRES_PASSWORD=micro
            - POSTGRES_DB=micro
        volumes:
            - pgdata:/var/lib/postgresql/data
    
    nginx:
        image: nginx:latest
        restart: on-failure
        networks:
             - api-micro
        ports:
             - 9099:9099
             - 80:80
        volumes:
             - ./nginx.conf:/etc/nginx/nginx.conf

    auth-service:
        image: hakimamarullah/auth-service-nestjs:v1.0.0
        pull_policy: always
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        env_file: .env.auth.docker
        networks:
            - api-micro
        depends_on:
            - dbmicro
    api-key-management:
        image: hakimamarullah/api-key-management-service-nestjs:v1.0.0
        pull_policy: always
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        env_file: .env.api-key-management.docker
        networks:
            - api-micro
        depends_on:
            - auth-service
            - dbmicro
    api-wilayah-service:
         image: hakimamarullah/api-wilayah-ri-nestjs:v1.0.0
         pull_policy: always
         deploy:
           mode: replicated
           replicas: 2
           restart_policy:
             condition: on-failure
         env_file: .env.api-wilayah.docker
         networks:
            - api-micro
         depends_on:
            - api-key-management
            - dbmicro
    payment-service:
         image: hakimamarullah/payment-service-nestjs:v1.0.0
         pull_policy: always
         deploy:
           mode: replicated
           replicas: 1
           restart_policy:
             condition: on-failure
         env_file: .env.payment-service.docker
         networks:
            - api-micro
         depends_on:
            - auth-service
            - dbmicro

    wilayah-ri-fe:
         image: hakimamarullah/wilayah-ri-fe:v1.0.0
         pull_policy: always
         deploy:
           mode: replicated
           replicas: 1
           restart_policy:
             condition: on-failure
         networks:
            - api-micro


volumes:
    pgdata: {}

networks:
    api-micro: