apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starline-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: transactions-svc-dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: transactions-svc
            port:
              number: 80