# This workflow will build a Java project with Maven, build Docker image, and deploy to VPS
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Build and Push Docker Image

on:
  push:
    tags: [ "v*" ]  # Trigger on tags

jobs:
  build_and_push:
    name: Build and Push Docker image
    # Only build on tag pushes
    if: startsWith(github.ref, 'refs/tags/v')
    environment: production
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-name: ${{ vars.DOCKER_IMAGE_NAME }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK (if needed for build context)
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Adjust to your Java version
          distribution: 'temurin'

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_IMAGE_NAME }}
          tags: |
            # Use tag name for tagged releases
            type=ref,event=tag
            # Use 'latest' for tagged releases
            type=raw,value=latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}
