name: Run Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker is running
        run: docker info

      - name: Run Tests
        run: mvn verify -Dspring.profiles.active=test
