name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24-dind
        ports:
          - 2375:2375
        options: >-
          --privileged
          --name dind
          --entrypoint dockerd-entrypoint.sh
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Docker client
        run: |
          echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV
          echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV
          docker info

      - name: Run Tests
        run: mvn verify -Dspring.profiles.active=test
